# Generated by Django 4.0.2 on 2022-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('public', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=20)),
            ],
        ),
    ]