# Generated by Django 4.0.2 on 2022-03-19 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('school', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('', '학년을 선택하세요.'), ('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년'), ('5', '5학년'), ('6', '6학년'), ('동아리', '동아리')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, upload_to='pic')),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(choices=[('open', '정상'), ('closed', '삭제')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(blank=True, related_name='classroom', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]