# Generated by Django 4.0.2 on 2022-03-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('pending', '진행 중'), ('success', '완결'), ('failure', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replay', to='posts.post')),
            ],
        ),
    ]