# Generated by Django 4.0.2 on 2022-03-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('relays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='relay', to='posts.post'),
        ),
    ]